name: akademi_gorev_takip
description: A Flutter app made for OUA.

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.0
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  flutter_local_notifications: ^13.0.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true



  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/oualogo.png
    - assets/girisimvakfi.png
    - assets/sanayib.png
    - assets/dijitaldonusum.png
    - assets/t3.png
    - assets/google.png
    - assets/icon.png
